backend/modules/documentation/models/Documentations.php
<?php

namespace backend\modules\documentation\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "yiidoc_documentations".
 *
 * @property integer $id
 * @property integer $text
 * @property string $title
 * @property integer $status
 * @property string $updated_at
 * @property string $created_at
 * @property Sections[] $sections
 * @property string $author_name
 * @property string $author_profile
 * @property string $support_link
 * @property string $support_text
 * @property string $header_text_color
 * @property string $header_bg_color
 *
 */
class Documentations extends \yii\db\ActiveRecord
{
    public $text;
    public $sections;

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function beforeSave($insert)
    {
        if (preg_match('~http://~', $this->author_profile))
            $this->author_profile = preg_replace('~http://~', '', $this->author_profile);
        if (preg_match('~http://~', $this->support_link))
            $this->support_link = preg_replace('~http://~', '', $this->support_link);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function afterSave($insert, $changedAttributes)
    {
        $post = Yii::$app->request->post('Documentations');
        Sections::deleteAll(['documentation_id' => $this->id]);
        $i = 0;
        foreach ($post['sections'] as $key => $value) {
            ++$i;
            $model = new Sections();
            $model->id = $key;
            $model->documentation_id = $this->id;
            $model->name = $value;
            $model->sort_id = $i;
            $model->text = $post['text'][$key];
            $model->save();
        }

        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%documentations}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['status'], 'integer',],
            [['header_text_color', 'header_bg_color', 'support_link', 'author_name', 'author_profile'], 'string'],
            [['title', 'updated_at', 'created_at'], 'string', 'max' => 255],
            [['title'], 'required'],
            [['sections'], 'required', 'message' => 'Please create minimum 1 section']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'status' => 'Status',
            'updated_at' => 'Updated At',
            'created_at' => 'Created At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSections()
    {
        return $this->hasMany(Sections::className(), ['documentation_id' => 'id']);
    }
}

backend/modules/documentation/controllers/DocumentationsController.php
<?php

namespace backend\modules\documentation\controllers;

use backend\modules\documentation\models\Sections;
use backend\modules\documentation\widgets\DocumentationWidget;
use Yii;
use backend\modules\documentation\models\Documentations;
use backend\modules\documentation\models\DocumentationsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use kartik\mpdf\Pdf;


/**
 * DocumentationsController implements the CRUD actions for Documentations model.
 */
class DocumentationsController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }


    /**
     * Lists all Documentations models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new DocumentationsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Documentation PDF.
     * @param integer $id
     * @return mixed
     */
    public function actionPdfGen($id)
    {

        $pdf = Yii::$app->pdf;
        $pdf->content = DocumentationWidget::widget(['id' => $id, 'showMenu' => false]);;
        return $pdf->render();


    }

    /**
     * Displays a single Documentations model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Documentations model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Documentations();
        $statusList = array('0' => 'Private', '1' => 'Published', '2' => 'Draft', '3' => 'Trash');
        $lastSectionId = Sections::find()->orderBy('id DESC')->all() ? Sections::find()->orderBy('id DESC')->limit(1)->one() : 0;
        if($lastSectionId != null) {
            $lastSectionId = $lastSectionId->id;
        }
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', compact('model', 'statusList', 'lastSectionId'));
        }
    }

    public function actions()
    {

        return [
            'browse-images' => [
                'class' => 'bajadev\ckeditor\actions\BrowseAction',
                'url' => '/images/uploads/',
                'path' => '@frontend/web/images/uploads/',
            ],
            'upload-images' => [
                'class' => 'bajadev\ckeditor\actions\UploadAction',
                'url' => '/images/uploads/',
                'path' => '@frontend/web/images/uploads/',
            ],
        ];
    }


    /**
     * Updates an existing Documentations model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $statusList = array('0' => 'Private', '1' => 'Published', '2' => 'Draft', '3' => 'Trash');
        $lastSectionId = Sections::find()->orderBy('id DESC')->all() ? Sections::find()->orderBy('id DESC')->limit(1)->one() : 0;
        if($lastSectionId != null) {
            $lastSectionId = $lastSectionId->id;
        }
        $currentSections = Sections::find()->where(['documentation_id' => $model->id])->orderBy('sort_id ASC')->all();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', compact('model', 'statusList', 'lastSectionId', 'currentSections'));
        }
    }

    /**
     * Deletes an existing Documentations model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Documentations model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Documentations the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Documentations::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/modules/documentation/views/documentations/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

use backend\modules\documentation\assets\DocumentationAsset;

DocumentationAsset::register($this);


/* @var $this yii\web\View */
/* @var $model backend\modules\documentation\models\Documentations */
/* @var $form yii\widgets\ActiveForm */
/* @var $lastSectionId number */
/* @var $statusList array */
?>

<div class="documentations-form">
    <?php $form = ActiveForm::begin(); ?>
    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>
    <?php $model->status = 1 ?>
    <?= $form->field($model, 'status')->dropDownList($statusList) ?>
    <div class="panel-group" id="accordion">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo"><span
                            class="glyphicon glyphicon-th-list">
                            </span> Basic Info</a>
                </h4>
            </div>
            <div id="collapseTwo" class="panel-collapse collapse">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <?= $form->field($model, 'support_text')->textInput(['maxlength' => true]) ?>
                                <?= $form->field($model, 'support_link')->textInput(['maxlength' => true]) ?>
                                <?= $form->field($model, 'author_name')->textInput(['maxlength' => true]) ?>
                                <?= $form->field($model, 'author_profile')->textInput(['maxlength' => true]) ?>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <?= $form->field($model, 'version')->textInput(['maxlength' => true]) ?>
                                <?= $form->field($model, 'header_bg_color')->widget(\kartik\color\ColorInput::classname(), [
                                    'options' => ['placeholder' => 'Select color ...'],
                                ]);
                                ?>
                                <?= $form->field($model, 'header_text_color')->widget(\kartik\color\ColorInput::classname(), [
                                    'options' => ['placeholder' => 'Select color ...'],
                                ]); ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid nonpadding">
        <div class="row">
            <div class="col-md-4" id="sections">
                <input type="text" name="Documentations[sections]" onsubmit="return false" id="newSecName"
                       placeholder="Section Name"
                       class="form-control" style="margin-bottom:10px">
                <span class="addSection">Add a New Section</span>
                <div id="loadSections">
                    <ul class="sortUl">
                        <?php
                        if (isset($currentSections))
                            foreach ($currentSections as $section) {
                                echo '<li data-section-id="' . $section->id . '"><span><span style="width:100px;overflow: hidden;text-overflow: ellipsis;" class = "sectionN' . $section->id . '">' . $section->name . '</span></span><span class="rightButtons"><a class="delt"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a></span><input class="hiddenSecIdd'. $section->id .'" type="hidden" name = "Documentations[sections][' . $section->id . ']" value="' . $section->name . '"></li>';
                            }
                        ?>
                    </ul>
                </div>
            </div>

            <div class="col-md-8">
                <div class="container-fluid sectionInfo">
                    <div class="row">
                        <div class="col-md-3 col-sm-12 col-xs-12" style="text-align:right;padding-top:5px;">
                            Section
                        </div>
                        <div class="col-md-9 col-sm-12 col-xs-12">
                            <input type="hidden" id="hdddd">
                            <input style="width:40%;background: rgba(0,0,0,0.8);border:0;color:#ffffff" type="text" class="form-control ChangeSec">
                        </div>
                    </div>

                </div>
                <div id="sectionsTextAreas">
                    <?php
                    if (isset($currentSections))
                        foreach ($currentSections as $section) {
                            echo $form->field($model, 'text[' . $section->id . ']')->textarea(['class' => 'form-control sectionTextArea', 'value' => $section->text])->label(false);
                        }
                    ?>
                </div>
            </div>
        </div>
    </div>
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>
<input type="hidden" id="hidUrl" value="<?= \yii\helpers\Url::toRoute(['default/sections']) ?>">
<input type="hidden" id="hidSectionLastId" value="<?= $lastSectionId ?>">

backend/modules/documentation/views/documentations/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\modules\documentation\models\DocumentationsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="documentations-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'status') ?>

    <?= $form->field($model, 'updated_at') ?>

    <?= $form->field($model, 'created_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/modules/documentation/views/documentations/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\modules\documentation\models\Documentations */

$this->title = 'Create Documentations';
$this->params['breadcrumbs'][] = ['label' => 'Documentations', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="documentations-create">
    <h1><?= Html::encode($this->title) ?></h1>
    <?= $this->render('_form', compact('model', 'statusList', 'lastSectionId')) ?>
</div>

backend/modules/documentation/views/documentations/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\modules\documentation\models\DocumentationsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Documentations';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="documentations-index">


    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Documentations', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'title',
            [
                'attribute' => 'status',
                'value' => function ($model) {
                    /* @var $model backend\modules\documentation\models\Documentations */
                    if (isset($model->status)) {
                        if ($model->status == 0)
                            return 'Private';
                        else if ($model->status == 1)
                            return 'Published';
                    } else {
                        return 'Published';
                    }

                }
            ],
            [
                'attribute' => 'updated_at',
                'value' => function ($model) {
                    /* @var $model backend\modules\documentation\models\Documentations */
                    if ($model->updated_at)
                        return Yii::$app->formatter->asDate($model->updated_at, 'dd-MM-yyyy');
                    else
                        return 'Date';
                },
                'filter' => \yii\jui\DatePicker::widget([
                    'model' => $searchModel,
                    'attribute' => 'updated_at',
                    'language' => 'ru',
                    'options' => ['class' => 'form-control']
                ]),
                'format' => 'html',
            ],
            [
                'attribute' => 'created_at',
                'value' => function ($model) {
                    /* @var $model backend\modules\documentation\models\Documentations */
                    if ($model->created_at)
                        return Yii::$app->formatter->asDate($model->created_at, 'dd-MM-yyyy');
                    else
                        return 'Date';
                },
                'filter' => \yii\jui\DatePicker::widget([
                    'model' => $searchModel,
                    'attribute' => 'created_at',
                    'dateFormat' => 'dd-MM-yyyy',
                    'options' => ['class' => 'form-control']
                ]),
                'format' => 'html',
            ],
            ['class' => 'yii\grid\ActionColumn'],
            [
                'attribute' => '',
                'format' => 'html',
                'value' => function ($model) {
                    /* @var $model backend\modules\documentation\models\Documentations */
                    return Html::a('<i class="fa glyphicon glyphicon-download-alt"></i> PDF', \yii\helpers\Url::to(['documentations/pdf-gen', 'id' => $model->id]), [
                        'class'=>'btn btn-download-alt',
                        'target'=>'_blank',
                        'data-toggle'=>'tooltip',
                        'title'=>'Will open the generated PDF file in a new window'
                    ]);

                }
            ]
        ],
    ]); ?>
</div>

backend/modules/documentation/views/documentations/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\modules\documentation\models\Documentations */

$this->title = 'Update Documentations: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Documentations', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="documentations-update">

    <h1><?= Html::encode($this->title) ?></h1>
    <?= $this->render('_form', compact('model', 'statusList', 'lastSectionId', 'currentSections')) ?>

</div>

backend/modules/documentation/views/documentations/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use backend\modules\documentation\widgets\DocumentationWidget;

/* @var $this yii\web\View */
/* @var $model backend\modules\documentation\models\Documentations */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Documentations', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="documentations-view">


    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?php echo DocumentationWidget::widget(['id' => $model->id]); ?>


</div>